#  docker-compose.yml
version: '3.8'

services:
  portfolio:
    # Building image from the GitHub Container Registry on actions
    image: ghcr.io/marcosdgomes/dmc-devops-tools:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    networks:
      - app_network

networks:
  app_network:
    external: true