name: Build, Push, and Deploy via Ansible

on:
  push:
    branches:
      - main 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- PARTE 1: BUILD E PUSH DA IMAGEM ---
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      # --- PARTE 2: DEPLOY VIA ANSIBLE (CONTAINER) ---
      - name: Configure SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Run Ansible Playbook to Deploy (via Docker)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v ~/.ssh:/root/.ssh:ro \
            -w /workspace \
            --network host \
            quay.io/ansible/ansible-runner:latest \
            ansible-playbook \
              -i infra/inventory.ini \
              infra/install_portfolio.yml